---
title: "CzechVeg-OpenStrat"
format: html
---

CzechVeg-OpenStrat is a publicly available, geographically and environmentally stratified subset of the Czech Vegetation Database. It is more balanced and less biased than the entire database, and is therefore suitable for data analyses on the national and regional scales. The stratification process and choices are described [here](https://czechveg.github.io/DataProcessingTutorial/data_stratification.html), and the resampling procedure is described [here](https://czechveg.github.io/DataProcessingTutorial/data_resampling.html). For most analyses, the most appropriate taxonomy and nomenclature is CZECHVEG_ESY, which is harmonized across the dataset and merges taxonomically challenging and inconsistently recorded taxa into broader taxon concepts.

CzechVeg-OpenStrat is available only in CSV format (see the [Data processing tutorial](https://czechveg.github.io/DataProcessingTutorial/data_processing_tutorial.html)). For importing the CSV files to R, we recommend using readr::read_csv.

**Version 1.1**

-   Compiled on: 26 March 2026
-   Source database: CzechVeg-Open version 1.1
-   Size: 61,282 vegetation plots
-   DOI: <https:/doi.org/10.5281/zenodo.19231152>
-   Licence: Creative Commons Attribution 4.0 International ([CC-BY](https://creativecommons.org/licenses/by/4.0/))
-   Differences from the previous version (1.0): Version 1.1 contains the same vegetation plots as version 1.0, but adds some values that were previously missing and corrects minor errors.
-   Download:
    -   [Vegetation-plot species data in CSV format](https://zenodo.org/records/19231152/files/CzechVeg_OpenStrat_species_v1-1_2026-03-26.csv?download=1)
    -   [Vegetation-plot header data in CSV format](https://zenodo.org/records/19231152/files/CzechVeg_OpenStrat_headers_v1-1_2026-03-26.csv?download=1)
    -   [Taxonomic backbone](https://github.com/CzechVeg/CzechVeg.github.io/blob/main/Data/crosswalk_tables/table_nomenclature.csv) (a table for interpretation of taxon concepts and names)

**Previous versions**

1.0 - <https://doi.org/10.5281/zenodo.18289905>
