---
title: "CzechVeg-Open"
format: html
---

CzechVeg-Open is a publicly available, full version of the Czech Vegetation Database that contains all vegetation-plot records. The data description is available [here](https://czechveg.github.io/Data/data_description.html).

CzechVeg-Open is available in two formats: the Turboveg 2 format, which requires the [Turboveg 2](https://czechveg.github.io/Data/turboveg.html) program, and the CSV format (see the [Data processing tutorial](https://czechveg.github.io/DataProcessingTutorial/data_processing_tutorial.html)). For importing the CSV files to R, we recommend using readr::read_csv.

**Version 1.1**

-   Compiled on: 26 March 2026
-   Size: 117,739 vegetation plots
-   DOI: <https://doi.org/10.5281/zenodo.19231152>
-   Licence: Creative Commons Attribution 4.0 International ([CC-BY](https://creativecommons.org/licenses/by/4.0/))
-   Differences from the previous version (1.0): Version 1.1 contains the same vegetation plots as version 1.0, but adds some values that were previously missing and corrects minor errors.
-   Download:
    -   [Vegetation-plot species data in CSV format](https://zenodo.org/records/19231152/files/CzechVeg_Open_species_v1-1_2026-03-26.csv?download=1)
    -   [Vegetation-plot header data in CSV format](https://zenodo.org/records/19231152/files/CzechVeg-Open_headers_v1-1_2026-03-26.csv?download=1)
    -   [Vegetation-plot data in Turboveg 2 format](https://zenodo.org/records/19231152/files/TurbovegDbBackup_Czechveg-open-v1-1-2026-03-26.zip?download=1)
    -   [Turboveg species list](https://github.com/CzechVeg/CzechVeg.github.io/blob/main/About/files/popup.zip) (necessary for Turboveg 2)
    -   [Turboveg popup lists](https://github.com/CzechVeg/CzechVeg.github.io/blob/main/About/files/species.zip) (necessary for Turboveg 2)
    -   [Taxonomic backbone](https://github.com/CzechVeg/CzechVeg.github.io/blob/main/Data/crosswalk_tables/table_nomenclature.csv) (a table for interpretation of taxon concepts and names)

**Previous versions**

1.0 - <https://doi.org/10.5281/zenodo.18289905>
